export const PROFILE_PAGE = {
  RECIPE: 'RECIPE',
  FOLLOWING: 'FOLLOWING',
  FOLLOWER: 'FOLLOWER',
  SHOPPING_LIST: 'SHOPPING_LIST',
  COLLECTION: 'COLLECTION',
  INFO: 'INFO',
  CUSTOMIZE: 'CUSTOMIZE'
}
