export const PROFILE_PAGE = {
  RECIPE: 'RECIPE',
  FOLLOWING: 'FOLLOWING',
  FOLLOWER: 'FOLLOWER',
  SHOPPING_LIST: 'SHOPPING_LIST',
  COLLECTION: 'COLLECTION',
  INFO: 'INFO',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CUSTOMIZE: 'CUSTOMIZE',
  HISTORY: 'HISTORY'
}
